# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoldPrice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftCharts', '~> 0.6'
  # Pods for GoldPrice

  target 'GoldPriceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoldPriceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
